### ISSUE TITLE
Nanoid async generate

### ISSUE THREAD

**Issue by Extarys** [y-gagar1n/nanoid-good#7]
In nanoid you can use `nanoid/async/generate` for a custom alphabet and use the async feature.
This is not implemented in `nanoid-good`.

Would it be possible to implement this? As async would allow node to continue working in another portion of the code while nanoid generate the id.

**Comment by y-gagar1n** [comment]
Thanks for your contribution. I added support for async generation and new version 1.3.0 is released.
